server:
  port: 0


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/_inventry_db
    password: saurabh123
    username: saurabh
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  application:
    name: INVENTORY-SERVICE